void 0===Object.create&&(Object.create=function(b){function a(){}a.prototype=b;return new a});function f(b,a){for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c])}function g(b,a){for(;b instanceof h;)b=b.force(a);return b}function h(b){this.g=!1;this.value=b}h.prototype.force=function(b){return b?this.value():this.g?this.value:(this.value=this.value(),this.g=!0,this.value)};function l(b){this.value=b}
function m(b,a){var c=b[0],d=b[1];if("action"==c)return function(){return m(d[0],g(a,!0).value)};if("function"==c)return function(){var b=a,c=d[d.length-1],e=d.length;if(1<e){b=g(b,!0);if("automatic_function"==d){for(var k=0;k<arguments.length;k++)b=g(b(n(["automatic"],arguments[k])),!0);return m(["automatic"],b)}for(k=0;k<e-1&&b instanceof Function;k++)b=g(b(n(d[k],arguments[k])),!0);e=c[1];return"action"==c[0]?m(e[0],b.value):m(c,b)}throw Error("Nullary function?");};if("string"==c)return p(a);
if("list"==c){c=[];for(a=g(a);a instanceof q;)c.push(m(d[0],a.c)),a=g(a.f);return c}if("tuple"==c){c=[];a=g(a);for(var e=0;a instanceof q;)c.push(m(d[e++],a.c)),a=g(a.f);return c}if("defined"==c)return a=g(a),a instanceof r?void 0:m(d[0],a.b);if("nullable"==c)return a=g(a),a instanceof t?null:m(d[0],a.b);if("double"==c||"int"==c||"bool"==c)return g(a);if("ptr"==c)return a;if("unknown"==c)return m(["automatic"],a);if("automatic"==c&&a instanceof Function)return m(["function","automatic_function"],
a);if("automatic"==c||"user"==c){a=g(a);if(a instanceof q||null===a){for(c=[];a instanceof q;)c.push(m(["automatic"],a.c)),a=g(a.f);return c}return(c=a&&a.a&&u[a.a])?c(b,b[2],a):a}throw Error("Unhandled Fay->JS translation type: "+c);}var u={};function p(b){var a="";for(b=g(b);b instanceof q;)a+=g(b.c),b=g(b.f);return a}
function n(b,a){var c=b[0],d=b[1],e;if("action"==c)return new l(n(d[0],a));if("function"==c){var I=d[d.length-1],y=d.slice(0,-1);if(0<a.length){var z=function(b){return function(c){c=m(y[b.length],c);var d=b.concat([c]);return d.length==y.length?new h(function(){return n(I,a.apply(this,d))}):z(d)}};return z([])}return function(b){return n(["automatic"],a(m(["automatic"],b)))}}if("string"==c)return v(a);if("list"==c){var k=[];e=0;for(c=a.length;e<c;e++)k.push(n(d[0],a[e]));return v(k)}if("tuple"==
c){k=[];e=0;for(c=a.length;e<c;e++)k.push(n(d[e],a[e]));return v(k)}if("defined"==c)return void 0===a?new r:new w(n(d[0],a));if("nullable"==c)return null===a?new t:new x(n(d[0],a));if("int"==c){e=Math.round(a);if(e!==a)throw"Argument "+a+" is not an integer!";return e}if("double"==c||"bool"==c||"ptr"==c)return a;if("unknown"==c)return n(["automatic"],a);if("automatic"==c&&a instanceof Function){b=[["automatic"]];for(e=0;e<a.length;e++)b.push(["automatic"]);return n(["function",b],a)}if("automatic"==
c&&a instanceof Array){d=null;for(e=a.length-1;0<=e;e--)d=new q(n([c],a[e]),d);return d}if("automatic"==c||"user"==c)return a&&a.instance?(e=A[a.instance])?e(b,b[2],a):a:a;throw Error("Unhandled JS->Fay translation type: "+c);}var A={};function q(b,a){this.c=b;this.f=a}function v(b){for(var a=null,c=b.length-1;0<=c;c--)a=new q(b[c],a);return a}function B(b){this.b=b}B.prototype.a="Nullable";function x(b){return new h(function(){return new B(b)})}function t(){}t.prototype.a="Null";
function w(b){this.b=b}w.prototype.a="Defined";function r(){}r.prototype.a="Undefined";f(u,{Nullable:function(b,a,c){var d={instance:"Nullable"};b=m(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.b);void 0!==b&&(d.slot1=b);return d},Null:function(){return{instance:"Null"}},Defined:function(b,a,c){var d={instance:"Defined"};b=m(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.b);void 0!==b&&(d.slot1=b);return d},Undefined:function(){return{instance:"Undefined"}}});
f(A,{Nullable:function(b,a,c){return new B(n(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.slot1))},Null:function(){return new t},Defined:function(b,a,c){return new w(n(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.slot1))},Undefined:function(){return new r}});function C(b){this.b=b}C.prototype.a="Just";function D(){}D.prototype.a="Nothing";function E(b){this.b=b}E.prototype.a="Left";function F(b){this.b=b}F.prototype.a="Right";function G(){}G.prototype.a="GT";
function H(){}H.prototype.a="LT";function J(){}J.prototype.a="EQ";function K(b){return new h(function(){var a=n,c=p(b);console&&console.log&&console.log(c);return new l(a(["unknown"],void 0))})}
f(u,{Just:function(b,a,c){var d={instance:"Just"};b=m(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.b);void 0!==b&&(d.slot1=b);return d},Nothing:function(){return{instance:"Nothing"}},Left:function(b,a,c){var d={instance:"Left"};b=m(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.b);void 0!==b&&(d.slot1=b);return d},Right:function(b,a,c){var d={instance:"Right"};b=m(a&&a[1]?a[1]:"automatic"===b[0]?["automatic"]:["unknown"],c.b);void 0!==b&&(d.slot1=b);return d},GT:function(){return{instance:"GT"}},
LT:function(){return{instance:"LT"}},EQ:function(){return{instance:"EQ"}}});f(A,{Just:function(b,a,c){return new C(n(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.slot1))},Nothing:function(){return new D},Left:function(b,a,c){return new E(n(a&&a[0]?a[0]:"automatic"===b[0]?["automatic"]:["unknown"],c.slot1))},Right:function(b,a,c){return new F(n(a&&a[1]?a[1]:"automatic"===b[0]?["automatic"]:["unknown"],c.slot1))},GT:function(){return new G},LT:function(){return new H},EQ:function(){return new J}});
g(new h(function(){return g(K)(v("Hello World"))}),!0);
